added missing time.h header
While utils.cpp compiles with some (or most) compilers, Microsoft Visual C 2017 fails with the message below. This line will fix the error.

[build]   utils.cpp
[build] C:\Users\Hendrik\dev\libczi\Src\libCZI_UnitTests\utils.cpp(325): error C2039: "time": Ist kein Element von "`global namespace'" [C:\Users\Hendrik\dev\libczi\build\Src\libCZI_UnitTests\libCZI_UnitTests.vcxproj]
[build] C:\Users\Hendrik\dev\libczi\Src\libCZI_UnitTests\utils.cpp(325): error C3861: "time": Bezeichner wurde nicht gefunden. [C:\Users\Hendrik\dev\libczi\build\Src\libCZI_UnitTests\libCZI_UnitTests.vcxproj]